[alembic]
alembic init 
alembic revision -m "add db_test"
alembic upgrade head
alembic revision --autogenerate -m "add db_test224"

[poetry]
poetry init
poetry add package
poetry show tree
poetry update package
