"""update db

Revision ID: b26ca6550181
Revises: 44e9db2083c2
Create Date: 2024-07-26 18:17:07.300388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26ca6550181'
down_revision = '44e9db2083c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_catalog',
    sa.Column('name_cn', sa.String(length=128), nullable=True, comment='中文名'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='英文名'),
    sa.Column('catalog_code', sa.String(length=128), nullable=True, comment='目录编码'),
    sa.Column('parent_id', sa.String(length=255), nullable=True, comment='父级'),
    sa.Column('order_no', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示:1显示;0不显示'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=True, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_catalog_field',
    sa.Column('table_code', sa.Integer(), nullable=True, comment='表编码'),
    sa.Column('physical_table_name', sa.String(length=128), nullable=True, comment='物理表名'),
    sa.Column('name_en', sa.String(length=128), nullable=True, comment='字段英文名'),
    sa.Column('name_cn', sa.String(length=512), nullable=True, comment='字段中文名'),
    sa.Column('is_pk', sa.Boolean(), nullable=True, comment='是否主键:1:是;0:否'),
    sa.Column('is_show_list', sa.Boolean(), nullable=True, comment='是否在列表显示'),
    sa.Column('is_show_detail', sa.Boolean(), nullable=True, comment='是否在详情显示'),
    sa.Column('order_no', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('type', sa.String(length=128), nullable=True, comment='字段类型'),
    sa.Column('domain_value', sa.Text(), nullable=True, comment='域值'),
    sa.Column('is_image', sa.Boolean(), nullable=True, comment='是否以图片展示1:是;0:否'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=True, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_catalog_table',
    sa.Column('datasource_id', sa.String(length=255), nullable=True, comment='数据源ID'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='表中文名'),
    sa.Column('physical_table_name', sa.String(length=128), nullable=True, comment='物理表名'),
    sa.Column('logic_table_name', sa.String(length=128), nullable=True, comment='逻辑表名'),
    sa.Column('table_name_alias', sa.String(length=255), nullable=True, comment='表中文别名'),
    sa.Column('table_code', sa.Integer(), nullable=True, comment='表编码'),
    sa.Column('table_type', sa.String(length=64), nullable=True, comment='表类型'),
    sa.Column('is_open', sa.Boolean(), nullable=True, comment='是否公开;1-公开;0不公开'),
    sa.Column('is_edit', sa.Boolean(), nullable=True, comment='是否可编辑;1-可编辑;0不可编辑'),
    sa.Column('order_no', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=True, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_catalog_table_relational_info',
    sa.Column('catalog_code_id', sa.String(length=128), nullable=True, comment='目录编码ID'),
    sa.Column('tabl_code_id', sa.String(length=128), nullable=True, comment='表编码ID'),
    sa.Column('order_no', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示:1显示;0不显示'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=True, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_datasource_info',
    sa.Column('datasource_type_id', sa.String(), nullable=False, comment='数据源类型ID'),
    sa.Column('datasource_name', sa.String(length=255), nullable=False, comment='数据源名称'),
    sa.Column('host', sa.String(length=100), nullable=False, comment='数据源主机IP'),
    sa.Column('user_name', sa.String(length=255), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('connect_string', sa.String(length=500), nullable=False, comment='连接字符串'),
    sa.Column('driver_name', sa.String(length=500), nullable=False, comment='驱动名称'),
    sa.Column('default_db', sa.String(length=255), nullable=False, comment='默认连接库名'),
    sa.Column('driver_file_path', sa.String(length=500), nullable=False, comment='驱动绝对路径'),
    sa.Column('port', sa.Integer(), nullable=False, comment='端口'),
    sa.Column('creator', sa.String(length=255), nullable=False, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=False, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dk_datasource_type',
    sa.Column('type_name', sa.String(length=50), nullable=False, comment='数据源类型名称'),
    sa.Column('is_async', sa.Boolean(), nullable=False, comment='是否异步'),
    sa.Column('driver_lib', sa.String(length=50), nullable=False, comment='驱动库'),
    sa.Column('connect_string_default', sa.String(length=500), nullable=False, comment='默认连接字符串'),
    sa.Column('delete_status', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dk_datasource_type')
    op.drop_table('dk_datasource_info')
    op.drop_table('dk_catalog_table_relational_info')
    op.drop_table('dk_catalog_table')
    op.drop_table('dk_catalog_field')
    op.drop_table('dk_catalog')
    # ### end Alembic commands ###
