"""add update dk_datasource_type

Revision ID: 487af646e4bc
Revises: 5498792c4f1b
Create Date: 2023-10-13 11:58:17.975026

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '487af646e4bc'
down_revision = '5498792c4f1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dk_datasource_type', sa.Column('is_async', sa.Boolean(), nullable=True, comment='是否异步'))
    op.add_column('dk_datasource_type', sa.Column('driver_lib', sa.String(length=50), nullable=True, comment='驱动库'))
    op.add_column('dk_datasource_type', sa.Column('is_install', sa.Boolean(), nullable=True, comment='是否安装驱动'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dk_datasource_type', 'is_install')
    op.drop_column('dk_datasource_type', 'driver_lib')
    op.drop_column('dk_datasource_type', 'is_async')
    # ### end Alembic commands ###
