"""add db_test2266

Revision ID: 5498792c4f1b
Revises: 205c9c224817
Create Date: 2023-10-12 22:36:56.634213

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5498792c4f1b'
down_revision = '205c9c224817'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_test',
                    sa.Column('type_name', sa.String(length=50), nullable=True, comment='数据源类型名称'),
                    sa.Column('connect_string_default', sa.String(length=500), nullable=True, comment='默认连接字符串'),
                    sa.Column('delete_status', sa.Boolean(), nullable=True, comment='默认连接字符串'),
                    sa.Column('id', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_test')
    # ### end Alembic commands ###
