"""Added account dk_catalog_table_relational_info

Revision ID: 9bab7117f68b
Revises: 3fcc65297a81
Create Date: 2023-07-12 17:14:26.055430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bab7117f68b'
down_revision = '3fcc65297a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dk_catalog_table_relational_info',
    sa.Column('catalog_code_id', sa.String(length=128), nullable=True, comment='目录编码ID'),
    sa.Column('tabl_code_id', sa.String(length=128), nullable=True, comment='表编码ID'),
    sa.Column('order_no', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_show', sa.Boolean(), nullable=True, comment='是否显示:1显示;0不显示'),
    sa.Column('creator', sa.String(length=255), nullable=True, comment='创建者'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('last_modifier', sa.String(length=255), nullable=True, comment='上次修改用户'),
    sa.Column('last_modify_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='上次修改时间'),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dk_catalog_table_relational_info')
    # ### end Alembic commands ###
