"""delete column driver_lib

Revision ID: ac3111d4a4d9
Revises: 487af646e4bc
Create Date: 2023-10-13 16:35:29.077629

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ac3111d4a4d9'
down_revision = '487af646e4bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dk_datasource_type', 'is_install')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dk_datasource_type', sa.Column('is_install', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
