"""Added account table

Revision ID: c32dabf6ac11
Revises: 
Create Date: 2023-05-29 22:21:06.883433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32dabf6ac11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dk_datasource_type', sa.Column('delete_status', sa.Boolean(), nullable=True, comment='默认连接字符串'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dk_datasource_type', 'delete_status')
    # ### end Alembic commands ###
