"""delete column driver_lib

Revision ID: fa81880f41d2
Revises: 0881c79b165f
Create Date: 2023-10-17 12:19:56.092399

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fa81880f41d2'
down_revision = '0881c79b165f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
